/**
 * ==============================================================================
 * ⏯️ [DEV 1/DEV 3] PLAYBACK & OVERLAY HOST (app/screens/PlaybackScreen.tsx)
 * ==============================================================================
 * Purpose:
 *   This is where the magic happens. This file takes the JSON analysis and the
 *   stored Video, plays them together, and renders Dev 3's SVG mathematics.
 *
 * Responsibilities:
 *   1. Load the original user `.mp4` into `expo-av` <Video>.
 *   2. Stream ElevenLabs audio simultaneously in the background.
 *   3. Pause the video at the exact `mistake_timestamp_ms` returned by Gemini.
 *   4. Show the `<SVGOverlay>` component right when the video pauses.
 *   5. Provide a "Continue" button to resume playback and hide the SVG.
 *
 * Synchronization Trap & Hacks (CRITICAL):
 *   - The `<Video>` component updates state too slowly (every 500ms by default).
 *     You MUST set `progressUpdateIntervalMillis={50}`. Otherwise, the video
 *     will overshoot the mistake frame, pausing on frame 1900 instead of 1450,
 *     which completely breaks Dev 3's visual alignments.
 *   - Audio Ducking: You must run `Audio.setAudioModeAsync` to tell iOS to
 *     ignore the hardware Silent switch and disable Android background ducking,
 *     otherwise judges won't hear ElevenLabs!
 * ==============================================================================
 */
import React, { useState, useRef } from 'react';
import { View, StyleSheet, Button, LayoutChangeEvent } from 'react-native';
// import { Video } from 'expo-av';
import SVGOverlay from '../components/SVGOverlay';

// For testing SVGOverlay without the full pipeline: use mock visuals when no analysis is passed.
const MOCK_VISUALS = require('../data/mock_response.json').visuals;

export default function PlaybackScreen({ route, navigation }: any) {
    // `analysis` contains the massive JSON payload generated by `modal/main.py`.
    const analysis = route.params?.analysis ?? { visuals: MOCK_VISUALS };

    const videoRef = useRef(null);
    const [isPaused, setIsPaused] = useState(false);
    // Show overlay by default when using mock data so you can test SVGOverlay without pausing.
    const [showOverlay, setShowOverlay] = useState(!route.params?.analysis);
    const [videoLayout, setVideoLayout] = useState<{ width: number; height: number } | null>(null);

    const handleVideoLayout = (e: LayoutChangeEvent) => {
        const { width, height } = e.nativeEvent.layout;
        if (width > 0 && height > 0) setVideoLayout({ width, height });
    };

    // Todo - Implement `onPlaybackStatusUpdate` event listener here.
    // 1. If status.positionMillis >= analysis.mistake_timestamp_ms && !isPaused
    // 2. videoRef.current.pauseAsync()
    // 3. setIsPaused(true)
    // 4. setShowOverlay(true)

    const handleContinue = () => {
        // 1. Hide the SVG vectors IMMEDIATELY. They are calculated for a STATIC frame.
        // If you leave them on screen when the video plays, they float randomly off the body.
        setShowOverlay(false);

        // 2. Resume playback
        // videoRef.current.playAsync()
        setIsPaused(false);
    };

    return (
        <View style={styles.container}>
            {/* 
        Dev 1: Insert expo-av <Video> player here.
        Make sure the aspect ratio perfectly matches the <CameraView> ratio in 
        RecordingScreen so the dimensions mathematically align.
      */}
            <View style={styles.videoContainer} onLayout={handleVideoLayout}>
                <View style={styles.videoPlaceholder} />
                {showOverlay && (
                    <View style={StyleSheet.absoluteFill}>
                        <SVGOverlay data={analysis.visuals} videoLayout={videoLayout ?? undefined} />

                        <View style={styles.controls}>
                            <Button title="Continue" onPress={handleContinue} />
                        </View>
                    </View>
                )}
            </View>

        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    videoContainer: {
        width: '100%',
        aspectRatio: 16 / 9,
        backgroundColor: '#333',
    },
    videoPlaceholder: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#333', // Placeholder for video
    },
    controls: {
        position: 'absolute',
        bottom: 50,
        width: '100%',
        alignItems: 'center'
    }
});
