/**
 * ==============================================================================
 * ⏯️ [DEV 1/DEV 3] PLAYBACK & OVERLAY HOST (app/screens/PlaybackScreen.tsx)
 * ==============================================================================
 * Purpose:
 *   This is where the magic happens. This file takes the JSON analysis and the
 *   stored Video, plays them together, and renders Dev 3's SVG mathematics.
 *
 * Responsibilities:
 *   1. Load the original user `.mp4` into `expo-av` <Video>.
 *   2. Stream ElevenLabs audio simultaneously in the background.
 *   3. Pause the video at the exact `mistake_timestamp_ms` returned by Gemini.
 *   4. Show the `<SVGOverlay>` component right when the video pauses.
 *   5. Provide a "Continue" button to resume playback and hide the SVG.
 *
 * Synchronization Trap & Hacks (CRITICAL):
 *   - The `<Video>` component updates state too slowly (every 500ms by default).
 *     You MUST set `progressUpdateIntervalMillis={50}`. Otherwise, the video
 *     will overshoot the mistake frame, pausing on frame 1900 instead of 1450,
 *     which completely breaks Dev 3's visual alignments.
 *   - Audio Ducking: You must run `Audio.setAudioModeAsync` to tell iOS to
 *     ignore the hardware Silent switch and disable Android background ducking,
 *     otherwise judges won't hear ElevenLabs!
 * ==============================================================================
 */
import React, { useState, useRef } from 'react';
import { View, StyleSheet, Button } from 'react-native';
// import { Video } from 'expo-av';
import SVGOverlay from '../components/SVGOverlay';

export default function PlaybackScreen({ route, navigation }: any) {
    // `analysis` contains the massive JSON payload generated by `modal/main.py`.
    const { analysis } = route.params;

    const videoRef = useRef(null);
    const [isPaused, setIsPaused] = useState(false);
    const [showOverlay, setShowOverlay] = useState(false);

    // Todo - Implement `onPlaybackStatusUpdate` event listener here.
    // 1. If status.positionMillis >= analysis.mistake_timestamp_ms && !isPaused
    // 2. videoRef.current.pauseAsync()
    // 3. setIsPaused(true)
    // 4. setShowOverlay(true)

    const handleContinue = () => {
        // 1. Hide the SVG vectors IMMEDIATELY. They are calculated for a STATIC frame.
        // If you leave them on screen when the video plays, they float randomly off the body.
        setShowOverlay(false);

        // 2. Resume playback
        // videoRef.current.playAsync()
        setIsPaused(false);
    };

    return (
        <View style={styles.container}>
            {/* 
        Dev 1: Insert expo-av <Video> player here.
        Make sure the aspect ratio perfectly matches the <CameraView> ratio in 
        RecordingScreen so the dimensions mathematically align.
      */}
            <View style={styles.videoPlaceholder} />

            {/* 
        Dev 3: SVG Math happens inside here. 
        It is rendered dynamically based on the JSON `analysis.visuals`.
      */}
            {showOverlay && (
                <View style={StyleSheet.absoluteFill}>
                    <SVGOverlay data={analysis.visuals} />

                    <View style={styles.controls}>
                        <Button title="Continue" onPress={handleContinue} />
                    </View>
                </View>
            )}
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    videoPlaceholder: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#333', // Placeholder for video
    },
    controls: {
        position: 'absolute',
        bottom: 50,
        width: '100%',
        alignItems: 'center'
    }
});
